slam_toolbox:
  ros__parameters:
    use_sim_time: true
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: scan
    resolution: 0.05
    use_scan_matching: true
    mode: mapping
    use_slam_mode: true
    enable_interactive_mode: false
    throttle_scans: 1
    transform_timeout: 0.2
    map_update_interval: 2.0
    max_laser_range: 15.0
    minimum_time_interval: 0.5
